[workspace]
resolver = "2"
members = ["amm-core", "amm-rpc"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"
repository = "https://github.com/21r21a33333/amm-rs"

[workspace.dependencies]
alloy-primitives = "1"
thiserror = "2"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
